### ISSUE TITLE
error occurs in running bash.sh and inc-repair.sh

### ISSUE THREAD

**Issue by lxxue** [jyi/ITSP#1]
# Description
I pull the docker image to reproduce the experiments result, but error keep occurring when I run the base.sh and inc-repair.sh, even some example shell scripts. 

# Info
System: Ubuntu 16.04.2
CPU: Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
Memory: 16GB

I followed the instructions(docker pull & run, both jayyi/itsp:0.0 and jayyi/itsp-no-angelix:0.0), and run some example shell script first. Most of the examples run successfully, although the output varies. But when I run the base.sh, many error occurs in some of the buggy programs, such as lab10-3237-303388.

# Reproduce the error
I modify the example shell script(base) to run the specific buggy program lab10-3237-303388 and get mainly 3 types of error:
* Error in `/ITSP-experiments/dataset-base/Lab-10/3237/303388_buggy/pr-session-0/workdir/src/prog': munmap_chunk(): invalid pointer: 0x00007ffe076db104 
* Error in `/ITSP-experiments/dataset-base/Lab-10/3237/303388_buggy/pr-session-0/workdir/src/prog': double free or corruption (out): 0x00007ffd5e86d920 
* Error in `/ITSP-experiments/dataset-base/Lab-10/3237/303388_buggy/pr-session-0/workdir/src/prog': double free or corruption (fasttop): 0x0000000000da5090  

![error](https://user-images.githubusercontent.com/22346567/28575033-52733eec-7182-11e7-827b-6ac3d40eb377.PNG)

when I run inc-repair-Lab-10-3239-303888.sh, there occurs the a prompt:
timeout: the monitored command dumped core

![timeout](https://user-images.githubusercontent.com/22346567/28575076-6c0db4d6-7182-11e7-8d2c-4bc48df5812c.PNG)

**Comment by jyi** [comment]
Thank you for the detailed report. 

It seems the errors you reported are raised from repair candidates generated by repair tools. Some of repair tools bash.sh invokes generate repair candidates and then test whether these repair candidates indeed pass all available tests. Some of the generated repair candidates may cause errors, and these repair candidates are rejected by the repair tool. 

In summary, it looks like the error messages you observed are raised from repair candidates which are rejected by the repair tool, and they are not the errors of bash.sh.

**Comment by lxxue** [comment]
So it's normal to see these errors while using ARP tools to repair programs with memory access, right?

Thank you for your answer.
